plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ilia.advanceclock'

    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId 'com.ilia.advanceclock'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
